[#173311623] Move counterfeit app files to Coinhouse
ArizenHQ/counterfeit pull request #36
Opened 2022-01-03 13:03 UTC by BenjaminG

https://www.pivotaltracker.com/story/show/173311623

2022-01-03 13:37 UTC, unflores approved these changes
Looks good. Remember you'll need to update your gemfile in the monolith for this to take action.

2022-01-03 13:42 UTC, unflores commented on README.md
> +Simple tool based on [Webmock](https://github.com/bblimke/webmock) and [Sinatra](https://github.com/sinatra/sinatra) to quickly mock API endpoints
stub endpoints not mock them.

2022-01-04 16:04 UTC, vrenaudineau commented on lib/counterfeit.rb
> -require 'counterfeit/version'
Shouldn't we keep version ?

2022-01-04 16:04 UTC, vrenaudineau commented on lib/counterfeit/info/app.rb
> -  module Info
Isn't this supposed to stay, like a status service ?

2022-01-04 18:04 UTC, vrenaudineau requested changes

2022-01-04 18:04 UTC, vrenaudineau commented on lib/counterfeit/info/views/index.haml
> -!!!  XML
This file is needed to render `haml :index`

2022-01-04 18:18 UTC, vrenaudineau approved these changes

2022-01-05 09:27 UTC, merged